# Generated by Django 5.1.5 on 2025-01-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userzodiac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userzodiac',
            name='profile',
        ),
    ]
